This is the basic jupyter notebook in vscode

In [1]:
print("Hello, World!")

Hello, World!


In [17]:
import numpy as np
nparray = np.array(1)
print(nparray.ndim)
# Vector
nparray = np.array([1, 2, 3])
print(nparray.ndim)
# Matrix
nparray = np.array([[1, 2, 3], [3, 4, 5]])
print(nparray.ndim)
print(nparray)
# 3-D Tensor (Image, collection of matrices and three channels RGB)
nparray = np.array([[[1, 2, 3], [3, 4, 5]],[[6, 7, 8], [9, 10, 11]]])
print(nparray.ndim)
print(nparray)
# 4-D Tensor (Collection of images)
nparray = np.array([[[[1, 2, 3], [3, 4, 5]],[[6, 7, 8], [9, 10, 11]]],[[[12, 12, 13], [14, 15, 16]],[[17, 18, 19], [20, 21, 22]]]])
print(nparray.ndim)
print(nparray)
# 5-D Tensor (video, collection of images in one frame and then collection of frames  in a video)
nparray = np.array([[[[[1, 2, 3], [3, 4, 5]],[[6, 7, 8], [9, 10, 11]]],[[[12, 12, 13], [14, 15, 16]],[[17, 18, 19], [20, 21, 22]]]],[[[[13, 24, 25], [26, 27, 28]],[[29, 30, 31], [32, 33, 34]]],[[[35, 36, 37], [38, 39, 40]],[[41, 42, 43], [44, 45, 46]]]]])
print(nparray.ndim)
print(nparray)
print (np.shape(nparray))  # (2, 2, 2, 2, 3)
print (nparray.size)   # (2, 2, 2, 2, 3)

0
1
2
[[1 2 3]
 [3 4 5]]
3
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
4
[[[[ 1  2  3]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 12 13]
   [14 15 16]]

  [[17 18 19]
   [20 21 22]]]]
5
[[[[[ 1  2  3]
    [ 3  4  5]]

   [[ 6  7  8]
    [ 9 10 11]]]


  [[[12 12 13]
    [14 15 16]]

   [[17 18 19]
    [20 21 22]]]]



 [[[[13 24 25]
    [26 27 28]]

   [[29 30 31]
    [32 33 34]]]


  [[[35 36 37]
    [38 39 40]]

   [[41 42 43]
    [44 45 46]]]]]
(2, 2, 2, 2, 3)
48
