In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
arr1 = np.arange(0,20).reshape(4,5)
#print("Original Array: ", arr1)
arr2 = np.arange(21,41).reshape(4,5)
#print("Original Array: ", arr2)

arr1+arr2
print("Addition: ", arr1+arr2)


Addition:  [[21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]]


# now the broadcasting is, 
> operation between two different matrix with different size but it should be in this format m\*n with 1\*n

In [17]:
arr3 = np.arange(11, 19).reshape(4, 2)
print("Array 3: ", arr3)

#print("Addition: ", arr1+arr3)

arr4 = np.arange(11, 16).reshape(1, 5)
print("Array 3: ", arr3)

print("Addition: ", arr1+arr4)

Array 3:  [[11 12]
 [13 14]
 [15 16]
 [17 18]]
Array 3:  [[11 12]
 [13 14]
 [15 16]
 [17 18]]
Addition:  [[11 13 15 17 19]
 [16 18 20 22 24]
 [21 23 25 27 29]
 [26 28 30 32 34]]
